namespace INeed.Helpers
{
    public static class AppConstantsEN
    {
        public static TextResources Get()
        {
            return new TextResources
            {
                CompanyName = "INeed",
                Slogan = "Because we are characterized by professionalism",

                Layout = new LayoutResources
                {
                    Home = "Home",
                    Privacy = "Privacy",
                    Questionnaires = "Questionnaires",
                    Contact = "Contact",
                    PrivacyPolicy = "Privacy Policy",
                    Terms = "Terms of Service",
                    CookieHeader = "Cookies",
                    CookieBody = "We use cookies to ensure best experience.",
                    CookieButton = "Accept"
                },

                Labels = new LabelResources
                {
                    YourEmailPlaceholder = "Your email address",
                    MessagePlaceholder = "Type your message here...",
                    EmailPlaceholder = "Email address",
                    FirstName = "First Name",
                    Woman = "Woman",
                    Man = "Man",
                    Category = "Category",
                    ResultScore = "Score"
                },

                Buttons = new ButtonResources
                {
                    SendMessage = "Send Message",
                    Delete = "Delete my data",
                    Back = "Go Back",
                    BackToHome = "Back to Home",
                    Continue = "Next",
                    SendAnswers = "Finish and see results",
                    SendResults = "Send results via email",
                    Start = "Start"
                },

                PolicyContent = new PolicyContentResources
                {
                    PrivacyAndCookies = "Privacy Policy content...",
                    Terms = "Terms content..."
                },

                Contact = new ContactResources
                {
                    PageTitle = "Contact Us",
                    Header = "We are here for you",
                    SubHeader = "Any questions? Write to us.",
                    OfficeName = "Customer Support",
                    Address = "al. Kilińskiego 12 p. 8 Płock, Poland",
                    Phone = "+48 123 456 789",
                    Email = "bok@ineed.com",
                    FormContactHeader = "Contact Form",
                    RodoConsent = "I consent to data processing.",
                    FormUnsubscribeHeader = "I want to delete my data",
                    ModalTitle = "Are you sure you want to delete your data?"
                },

                Fill = new FillResources
                {
                    PageTitle = "Questionnaire",
                    Step = "Question",
                    Of = "of",
                    SelectOption = "Select an option:",
                    Page = "Page",
                    NoQuestions = "No questions available.",
                    AlertPage = "Please answer all questions on this page.",
                    AlertAll = "Please answer all questions before sending."
                },

                Messages = new MessageResources
                {
                    Success = "Operation successful.",
                    Error = "An error occurred. Please try again.",
                    ValidationRequired = "This field is required.",
                    EmailSent = "Message has been sent.",
                    DataDeleted = "Your data has been deleted.",
                    RodoRequired = "You must consent to data processing (GDPR).",
                    NewMessage = "New message from user:",
                    ContactSuccess = "Your message has been sent successfully.",
                    ContactError = "Failed to send message. Please try again.",
                    FormIncomplete = "The form is incomplete.",
                    UnsubscribeSuccess = "Your email address has been removed from our database.",
                    EmailNotFound = "The provided email address was not found.",
                    Wyniki = "Your Results",
                    EmailThanks = "Thank you for completing the questionnaire. Below are your results.",
                    GeneratedBy = "This message was automatically generated by the INeed system.",
                    YourResults = "Your results:",
                    EmailSentSuccess = "The results have been sent to the provided email address.",
                    EmailSentError = "An error occurred while sending the email.",

                    // NOWE
                    CombinedResultsTitle = "Your Combined Results",
                    ResultsForIdBody = "Below are all survey results associated with identifier",
                    UnknownSurvey = "Unknown Survey",
                    FillDate = "Date filled",
                    NoResultsFound = "No results found for your identifier.",
                    EmailRequired = "Please provide an email address.",
                    AllResultsSentSuccess = "All results have been sent to the provided email address."
                },

                Result = new ResultResources
                {
                    PageTitle = "Your Result",
                    Header = "Your Result",
                    SubHeader = "Below you will find a detailed analysis of your answers.",
                    SaveHeader = "Save your result",
                    SaveSubHeader = "Enter your email address to receive a permanent copy of the results and interpretation.",
                    RodoConsent = "I accept the",
                    And = "and",
                    AcceptTerms = ", and I agree to data processing for sending the result."
                },

                Home = new HomeResources
                {
                    Header = "Available Questionnaires",
                    SubHeader = "Select a questionnaire from the list below to start the assessment process."
                }
            };
        }
    }
}